---
# manage dnf bases on the distribution

- name: Manage dnf automatic version 4 for centos8
  import_tasks: dnf4.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution == "CentOS" and ansible_distribution_major_version | int <= 8

- name: Manage dnf automatic version 4 for centos9
  import_tasks: dnf4.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution == "CentOS" and ansible_distribution_major_version | int == 9

- name: Manage dnf automatic version 5 for fedora40
  import_tasks: dnf4.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution == "Fedora" and ansible_distribution_major_version | int == 40

- name: Manage dnf automatic version 5 for fedora41
  import_tasks: dnf5.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution == "Fedora" and ansible_distribution_major_version | int >= 41

