---
- set_fact:
    dnf_automatic_package_name: dnf-automatic
    dnf_automatic_systemd_timer: dnf-automatic-install.timer
  when:
    - ansible_pkg_mgr == "dnf4"

- set_fact:
    dnf_automatic_package_name: dnf5-plugin-automatic
    dnf_automatic_systemd_timer: dnf5-automatic.timer
  when:
    - ansible_pkg_mgr == "dnf5"

# ----- ----- ----- ----- -----

- name: "Install {{ dnf_automatic_package_name }} package"
  ansible.builtin.package:
    name: "{{ dnf_automatic_package_name }}"
    state: present

- name: Deploy dnf-automatic configuration file
  ansible.builtin.template:
    src: automatic.conf.j2
    dest: /etc/dnf/automatic.conf
    mode: "0644"

- name: Create dnf-automatic timer override directory
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ dnf_automatic_systemd_timer }}.d"
    state: "directory"
    mode: "0755"
  when: dnf_automatic_timer_OnCalendar != "6:00"

- name: Deploy dnf-automatic timer override file
  ansible.builtin.template:
    src: timer_oncalendar.conf.j2
    dest: "/etc/systemd/system/{{ dnf_automatic_systemd_timer }}.d/timer_oncalendar.conf"
    mode: "0644"
  notify: Reload systemd
  when: dnf_automatic_timer_OnCalendar != "6:00"

- name: Remove dnf-automatic timer override file
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ dnf_automatic_systemd_timer }}.d"
    state: absent
  notify: Reload systemd
  when: dnf_automatic_timer_OnCalendar == "6:00"

- name: Perform auto reboot specific tasks
  when: dnf_automatic_reboot | bool
  block:
    - name: Install dependencies needed for reboot
      ansible.builtin.package:
        name: "{{ dnf_automatic_reboot_dependencies }}"
        state: present

    - name: Deploy service and timer units
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "/etc/systemd/system/{{ item }}"
        owner: root
        group: root
        mode: "0644"
      loop:
        - dnf-automatic-reboot.service
        - dnf-automatic-reboot.timer
      notify: Reload systemd

- name: "Check status of {{ dnf_automatic_systemd_timer }}"
  ansible.builtin.systemd:
    name: "{{ dnf_automatic_systemd_timer }}"
  register: dnf_automatic_install_timer

- name: Start and enable systemd timer for dnf-automatic
  ansible.builtin.service:
    name: "{{ dnf_automatic_systemd_timer }}"
    state: started
    enabled: true
  # run always if not in check mode or if the timer unit exists
  # regardless of the check mode state
  when: not ansible_check_mode or
        dnf_automatic_install_timer.status["LoadState"] == "loaded"

- name: Check status of dnf-automatic-reboot.timer
  ansible.builtin.systemd:
    name: dnf-automatic-reboot.timer
  register: dnf_automatic_reboot_timer

- name: Set timer state for auto reboot
  ansible.builtin.systemd:
    name: dnf-automatic-reboot.timer
    state: "{{ dnf_automatic_reboot | ternary('started', 'stopped') }}"
    enabled: "{{ dnf_automatic_reboot }}"
    masked: false
  # run always if not in check mode and the auto reboot is enabled
  # or if the timer unit exists regardless of the check mode state
  when: (not ansible_check_mode and dnf_automatic_reboot) or
        dnf_automatic_reboot_timer.status["LoadState"] == "loaded"
