---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: "dnf-automatic-${image:-fedora}-${tag:-latest}"
    image: "${namespace:-quay.io/fedora}/${image:-fedora}:${tag:-latest}"
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: false
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
