# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

ENV container=docker

RUN dnf -y install systemd && dnf clean all && \
    systemctl mask systemd-remount-fs.service \
                   dev-hugepages.mount \
                   sys-fs-fuse-connections.mount \
                   systemd-logind.service \
                   getty.target \
                   console-getty.service && \
    systemctl disable dnf-makecache.timer \
                      dnf-makecache.service

VOLUME ["/sys/fs/cgroup"]
CMD ["/sbin/init"]
